### ISSUE TITLE
Initial feature list

### ISSUE THREAD

**Issue by stuf** [rensouhou/dockyard-app#1]
A rough list of core features that are very much _would like_-tier to be considered "initial release complete".
## Application back-end
- [x] ~~Finalise state shape (#4)~~
- [x] ~~Implement logging (#5)~~
## Timers
- [ ] Mission/expedition timers
- [ ] Construction/ship timers
- [ ] Repair timers
- [ ] Morale timers
- [ ] Front-end timer component (#2)
- [ ] Persist timers between closing down the application (#3)
## Logging
- [ ] Event logging component (DB)
- [ ] Log construction (ships, items, improvements)
- [ ] Log sorties
- [ ] Log PVPs
## Battle
- [ ] Prediction / damage calculation
## Generic front-end
- [ ] Progress bar component
- [ ] Morale component
- [ ] Quest list
- [ ] Ship docks (construction, repair)
- [ ] Roughly customizable interface — (simple on/off for `x, y, z`)
## Overviews
- [ ] Front-end for overview
- [ ] Ship roster
- [ ] Slotitem/equipment list
- [ ] Filtering of lists (including locked, not maxed-out, not-lv1)
