### ISSUE TITLE
Progression tracking

### ISSUE THREAD

**Issue by stuf** [rensouhou/dockyard-app#6]
This is a broader issue and not 100% constrained to _quest progression_, but progression in the Dockyard application in general. There are some other parts of the application that will be using progression tracking in some way.

Currently quests et.al. are not being actively tracked, and any progression in quest state or status gets only updated when data is received from the API. This means, for example, that quests in the quest list get marked as complete only when going to the quest list and loading the quest list page where the quest is located at.

Figure out how to implement progression tracking in (as close to) such a way, that:
- [ ] reducers stay pure; no using of data from outside of the reducing function
- [ ] is extendable in some way; progression requirements can be changed without having to poke in the core application code
- [ ] reacts only to dispatched actions; no updating of state outside of the _action-reducer-store scope_.

One option for implementing this may be delegating progression tracking to a middleware that will get a `Map` of handlers that may update the application state.

This probably opens a can of worms in terms of what are "core handlers" that are required, and what's additional sugar on top.
